### ISSUE TITLE
What if... new footnote is inserted before the first footnote?

### ISSUE THREAD

**Issue by jerviscui** [MichaBrugger/obsidian-footnotes#10]
Can use Linter to update the footnote order when saving.
https://github.com/platers/obsidian-linter

**Comment by yuchuanghui** [comment]
The tidy footnotes plugin does better than the linter plugin. It can resort the footnotes, not only the keys.

**Comment by jerviscui** [comment]
Yes, I want to trigger resort when the file is saved.

**Comment by Comprehensive-Jason** [comment]
@jerviscui Is this still a feature you want in this plugin?

**Comment by Comprehensive-Jason** [comment]
I have decided to point users to Linter in the README and Plugin wiki if they want this feature.

**Comment by Comprehensive-Jason** [comment]
This has been added to the plugin now in 0.2.0.
