### ISSUE TITLE
FR: Multiple references to one footnote

### ISSUE THREAD

**Issue by Calorion** [MichaBrugger/obsidian-footnotes#11]
Obsidian supports multiple references to the same footnote, but obsidian-footnotes does not. 

```
Text[^1], and more text[^1]

[^1]: The footnote
```

In this situation, the plugin behaves normally with respect to the first reference, but when the insertion point is within the second reference, instead of jumping to the footnote, obsidian-footnotes attempts to create another footnote.

I would like it to just jump to the correct footnote. Ideally, it would also jump back to the footnote reference it came from, but if it just jumped back to the first reference that would be acceptable.

**Comment by daribock** [comment]
For me it works. If you have one or more references to the first footnote the footnote will be displayed with another number on the side:
![image](https://user-images.githubusercontent.com/57658125/222120948-c8bf5996-b7f9-4042-844b-5bfa6b7e303d.png)
The Footnote itself then has the link behind it:
![image](https://user-images.githubusercontent.com/57658125/222121255-204f5371-ad43-4096-986a-111d40736a4c.png)

So I think the plugin is already able to do the things you request. 🥳

**Comment by Calorion** [comment]
As I said, "Obsidian supports multiple references to the same footnote, but obsidian-footnotes does not." What you're experiencing is Obsidian's functionality in Reading view, not the plugin's functionality in Edit view.

**Comment by Comprehensive-Jason** [comment]
@Calorion I have fixed this bug in [my fork](https://github.com/Comprehensive-Jason/obsidian-footnotes). Until my pull request gets accepted, you can try it out using [Obsidian BRAT](https://github.com/TfTHacker/obsidian42-brat). Please make sure to read the README, as I have added new instructions for other new features. 

## My fix currently works as follows: 

### In this situation (cursor = ▊)
```
Text[^1], and more text[^1▊]

[^1]: The footnote
```
Hitting the hotkey once will jump the cursor to the footnote detail. 
```
Text[^1], and more text[^1]

[^1]: ▊The footnote
```
Hitting it again will jump the cursor to the first footnote marker.
```
Text[^1]▊, and more text[^1]

[^1]: The footnote
```

**Comment by Comprehensive-Jason** [comment]
My fix has been added to this plugin's latest release.
