### ISSUE TITLE
FR: Incorporate all features from Tidy Footnotes

### ISSUE THREAD

**Issue by Comprehensive-Jason** [MichaBrugger/obsidian-footnotes#14]
The [Tidy Footnotes plugin](https://github.com/charliecm/obsidian-tidy-footnotes) hasn't been updated in 2 years. 
It is a good idea to merge its features into this plugin. By doing so, this plugin will become a one-stop shop for all things footnote-related.

**Comment by Comprehensive-Jason** [comment]
Adding this feature will resolve #10

**Comment by Comprehensive-Jason** [comment]
It might be good to also look at the [Linter](https://github.com/platers/obsidian-linter) plugin's implementation of the same feature. 
On second thought, it may even be a better idea to direct users interested in this feature to Linter, as it has many more features for footnote and general formatting management.

**Comment by Comprehensive-Jason** [comment]
Linter's Re-Index Footnotes command changes both numeric and named footnotes, which is a problem for users who want to preserve their named footnotes and only re-index their numbered footnotes. 
For this reason, it is probably best to build a custom solution off of Tidy Footnotes inside this plugin.

**Comment by jerviscui** [comment]
Linter will run when saving the file.

**Comment by Comprehensive-Jason** [comment]
@jerviscui Does Linter already do what you want? If so, I will just put in an issue with the Linter dev asking him to only lint numeric footnotes.

**Comment by Comprehensive-Jason** [comment]
I have decided to point users to Linter in the README and Plugin wiki if they want this feature.

**Comment by Comprehensive-Jason** [comment]
I have decided to point users to Linter in the README and Plugin wiki if they want this feature.

**Comment by Comprehensive-Jason** [comment]
This has been added to the plugin now in 0.2.0.
