### ISSUE TITLE
FR: Add footnote popovers like the BetterFn plugin

### ISSUE THREAD

**Issue by Comprehensive-Jason** [MichaBrugger/obsidian-footnotes#16]
The [BetterFn plugin](https://github.com/aidenlx/better-fn) hasn't been updated in 2 years.
It is a good idea to merge its features into this plugin. By doing so, this plugin will become a one-stop shop for all things footnote-related.

**Comment by Comprehensive-Jason** [comment]
BetterFn's footnote popover will have to be somewhat rebuilt to work in both Live Preview and Reading mode.

**Comment by Comprehensive-Jason** [comment]
[Obsidian Latex Suite](https://github.com/artisticat1/obsidian-latex-suite) has a good preview feature that could be borrowed for this.

**Comment by Lepton-Lee** [comment]
I'm looking forward to it

**Comment by Lepton-Lee** [comment]
https://github.com/aidenlx/better-fn/pull/42

**Comment by Comprehensive-Jason** [comment]
@Lepton-Lee Thanks for bringing the new PR to my attention. I will put this on hold until the BetterFn plugin release supports Live Preview, after which I will close this.

**Comment by Comprehensive-Jason** [comment]
[Obsidian 1.6.0](https://obsidian.md/changelog/2024-05-09-desktop-v1.6.0/) adds a feature to page preview so that "Hovering over a footnote ID will now display a popup with the corresponding footnote". 
This makes the FR redundant.
