### ISSUE TITLE
New footnote is inserted next to the existed footnote instead of jumping to the footnote detail

### ISSUE THREAD

**Issue by web8823** [MichaBrugger/obsidian-footnotes#17]
Obsidian version: v1.2.8 (latest)
Plugin version 0.1.0

The issue occurs in the first footnote of each paragraph. I created a new vault to test it out. Please take a look at the video.

https://github.com/MichaBrugger/obsidian-footnotes/assets/93432430/7a55137d-1716-42ab-99db-72b308c63b26

**Comment by Comprehensive-Jason** [comment]
I've reproduced the issue. Is this the same issue you are having?

https://github.com/MichaBrugger/obsidian-footnotes/assets/68677082/01583203-d192-4a02-a9f7-3a54d6051c57


I believe it's a problem with the footnote-finding regex. I'll have it fixed soon.

**Comment by Comprehensive-Jason** [comment]
Fixed this issue in commit 940fa85
