### ISSUE TITLE
iPad Pro

### ISSUE THREAD

**Issue by rbsleyrer** [MichaBrugger/obsidian-footnotes#18]
Unable to enable the plugin on my iPad Pro after the update 😕
On Mac everything runs smooth.

**Comment by Comprehensive-Jason** [comment]
That's weird. What version of Obsidian are you using on your iPad?

Could you record a video of you trying to enable the plugin? Could you also try uninstalling and reinstalling? Could you also disable all your other plugins and see if the problem persists?

**Comment by Comprehensive-Jason** [comment]
Did it stop working after 0.1.0 or 0.1.1? The latest update, 0.1.1, was extremely minor. I only changed a few lines and moved the code around to better organize it, so there shouldn't be any new incompatibilities with iPad.

**Comment by Comprehensive-Jason** [comment]
Issue replicated, fixed in commit https://github.com/MichaBrugger/obsidian-footnotes/commit/6353558fda16e5a9c3c11a40a36fb268b36e2619
