### ISSUE TITLE
FR: Create footnote and highlight around selected text (sort of like comments)?

### ISSUE THREAD

**Issue by zweek** [MichaBrugger/obsidian-footnotes#24]
This might not be super in line with what this plugin is meant to be, but I've always thought that footnotes are about as close as vanilla obsidian gets to the way comments work in other apps like Notion & Google Docs, where you can highlight a piece of text and add a comment to it. I've used comments a ton in those apps and have missed it a little in obsidian

Current behavior with selected text is that the footnote is placed at the selection head, suggested behavior would look something like this:
```
==a very cool sentence with an even cooler footnote==[^1]
  ^ selection from                                ^ selection to
```

This would also combo super well with the popover feature suggested in #16

**Comment by Comprehensive-Jason** [comment]
Intriguing use case. I personally wouldn't recommend using footnotes as 'comments', as they could get cluttered amongst references and stuff you usually use footnotes for. 

There are already some incredibly cool commenting plugins in Obsidian. Both of the ones I mention below are being actively developed.

- [Obsidian Reading Comments](https://github.com/BumbrT/obsidian-reading-comments) uses HTML formatting to make slick basic comments that pop up when you hover over the selected text.       ![](https://raw.githubusercontent.com/BumbrT/obsidian-reading-comments/master/resources/create-comment-ru.gif)        ![](https://raw.githubusercontent.com/BumbrT/obsidian-reading-comments/master/resources/navigate-comment-ru.gif)


- [Obsidian CriticMarkup](https://github.com/fevol/obsidian-criticmarkup) uses CriticMarkup syntax with the end goal of Google Docs-level collaborative commenting features. It is currently in beta, so you can install and test it with [BRAT](https://github.com/TfTHacker/obsidian42-brat).       ![](https://cdn.discordapp.com/attachments/1082420499163918408/1145415490223743026/criticmarkup_view_v2.gif)

**Comment by zweek** [comment]
ooo, CriticMarkup does seem like exactly the kind of thing I was looking for for my own use case. And I do agree that conflating footnotes and references with comments is probably not the best idea and can get confusing very quickly. Happy to close this issue then
