### ISSUE TITLE
Add Hover Editor feature for footnotes

### ISSUE THREAD

**Issue by enonod** [MichaBrugger/obsidian-footnotes#29]
I have Footnote Shortcut v0.1.3. It is working. This comment is not about a baddy but could be a goody.
When I have a complete footnote [^1] and its associated note, I have found that if I put the cursor immediately in front of the ‘[’ and press virtually any key, a popup box appears, in the same way as when previewing a link, and it has the footnote number on line one and the footnote text on line two.
It appears to me that this action is not intended.
However, it is an excellently useful feature if it worked with hover instead of pressing a key.
I have Hover Editor installed but turned off, so I do not think it is related.
Is it possible to actually make it work as if it _were_ intended because I could certainly use it.

**Comment by Comprehensive-Jason** [comment]
That pop-up box is technically called 'Footnote Autosuggest'. It's kind of only supposed to show up when you type inside of a footnote marker, then lets you quickly autocomplete footnotes that you use repeatedly.

Right now, I don't have it coded perfectly, so it also shows up when you type immediately in front of a footnote like you mentioned. This is technically incorrect behavior.

I presume that you want this box to pop up when you hover over a footnote to replace Hover Editor?

**Comment by enonod** [comment]
Thank you for the response. Yes that would be superb. Hover Editor only pops up over a link to another page or block within a page, not a footnote. To have similar happen with Footnotes must be something everybody would like because they are a pain when having to scroll to the bottom of page and of course are distracting when inline.

I must apologise because I have not used the feature regarding suggestions and only had one footnote, thus not 'twigging'. Hopefully some variation might provide what is required.

This plugin seems to be superb in its automation and ease of use.

**Comment by enonod** [comment]
Sorry to trouble you but I have just tried it with two footnotes and it works with either one and in each case it only shows the footnote details for the one I click, so it is not showing two choices as I presume you are suggesting.

**Comment by Comprehensive-Jason** [comment]
Here's a demo of how it should work, tested in my vault: 

https://github.com/MichaBrugger/obsidian-footnotes/assets/68677082/3d449681-d9b3-4c8a-94a2-8701901e4182

**Comment by enonod** [comment]
Thank you for that. Firstly the situation I referred to was when using auto numbers for footnotes. When you use named footnotes I see on your video what I described for numbered but only the one with the same number (clearly). However I never used named footnotes. Having seen what you have just done, I tried naming but although the name appeared instead of a number at the source, I did not get the footnote at the bottom of the page and because I did not already have one, I did not get any suggestion either despite having the option turned on.
I then entered [^cast]: in the footnotes then retried a new named footnote source beginning with 'c' and I got the suggestion as you have showed.
1. The end result seems to be that your initial response applies for 'in front of'.
2. Named footnotes do not seem to create and so are manual at the destination instead of copying automatically what has been typed as the source name.
3. Am I correct or do I have a problem? 
4. Can this be modified to produce the 'Page Preview' or 'Hover Edit' popup?
By the way thank you for your time.

**Comment by enonod** [comment]
Sorry, just tested and realism item 2 above is not correct, I have to press the hotkey a second time when complete. So really we are back at the start and 1 & 4 apply.

**Comment by enonod** [comment]
Thank you for your kind attention

**Comment by Comprehensive-Jason** [comment]
Do you want to add a Hover Editor-like feature for footnotes or not? If so, please keep this issue open.

**Comment by enonod** [comment]
Sorry I am not familiar with Github I was advised by a forum to use it to contact you.
Please keep this open, I assumed the button was to end the conversation.

**Comment by Comprehensive-Jason** [comment]
I think Hover Editor now works on footnotes too. See here: 


https://github.com/MichaBrugger/obsidian-footnotes/assets/68677082/1b6a180b-6717-4237-9728-af8ac9d4295a
