### ISSUE TITLE
Footnote won't include link

### ISSUE THREAD

**Issue by dahearn** [MichaBrugger/obsidian-footnotes#30]
When I add external link to a YouTube video as the footnote, the footnote doesn't recognize the syntax as a link (and make it clickable with the external box-arrow icon).  I teethe syntax but copying it out of the footnote onto its own line and voila, it works.  It appears to be a footnote-specific issue.  

It may be an Obsidian issue and not a Footnotes plug-in issue.  See https://forum.obsidian.md/t/inline-footnotes-and-external-links/45260

Seems odd as links in footnotes doesn't seem like an edge case.

<img width="749" alt="Screenshot 2023-12-12 at 11 12 18 PM" src="https://github.com/MichaBrugger/obsidian-footnotes/assets/6889078/85428b5b-a691-431b-86b4-21f883e589d6">

**Comment by Comprehensive-Jason** [comment]
This is an Obsidian issue. My plugin does not alter this behavior in any way.

**Comment by dahearn** [comment]
Thanks sir!  Loving the plug-in.
