### ISSUE TITLE
Display of external links

### ISSUE THREAD

**Issue by jowitte** [MichaBrugger/obsidian-footnotes#38]
Right now external links in footnotes are shown as raw source:

<img width="560" alt="image" src="https://github.com/MichaBrugger/obsidian-footnotes/assets/8180200/ab33f198-de3a-4e1c-9768-01f63b4fcaf8">

I'd rather prefer them to be displayed like this as it is normally done in preview mode:

<img width="494" alt="image" src="https://github.com/MichaBrugger/obsidian-footnotes/assets/8180200/6c85cb03-052e-45f6-ae94-e23dac439aa4">

**Comment by borutzki** [comment]
The same goes for markdown-style links: 
<img width="703" alt="obraz" src="https://github.com/MichaBrugger/obsidian-footnotes/assets/63121296/45975b6c-52fc-4602-b444-c8a8a829a442">

**Comment by Comprehensive-Jason** [comment]
This feature has been added by Obsidian Native in v1.6.
