### ISSUE TITLE
Both number and text footnotes only display as numbers in Read view

### ISSUE THREAD

**Issue by THIS-Usr** [MichaBrugger/obsidian-footnotes#40]
Both number and text footnotes only display correctly in editing view.
But in read view they display only as numbers.

I cannot find a conflict with other plugins, but I could be wrong about this.
There is a possibility that some CSS in the .obsidian/snippets folder is interfering.
I am uncertain about this, too.

To keep it short here is a segment of Lorum Ipsum in English.

--
But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted[^Idea One]. The wise man[^Widom] therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures[^3], or else he endures pains to avoid worse pains.

[^1]: This is Latin
[^2]: There is a section mark but it does not show "Footnotes". Is that an option in settings? Actually it is.
[^Idea One]: Keep the text short so as to demonstrate only what is happening here.
[^Widom]: This is a desirable quality.
[^3]: The third note is found with pleasure.

Here is the above text before posting (rendering it) here, as it also appear in edit mode in Obsidian:-

<img width="590" alt="CleanShot 2024-04-19 at 17 20 38@2x" src="https://github.com/MichaBrugger/obsidian-footnotes/assets/1985103/bb2b0ccf-464c-46ef-97b8-e4b60fbab59d">

And here it is in read view in Obsidian.

<img width="732" alt="CleanShot 2024-04-19 at 17 08 13@2x" src="https://github.com/MichaBrugger/obsidian-footnotes/assets/1985103/5d7c8d6d-c247-4dc1-8a31-ad281beaafc9">

Here is the copied text from read view.

But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted[^Idea One]. The wise man[[3]](app://obsidian.md/index.html#fn-3-602866a332ee5320) therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures[[4]](app://obsidian.md/index.html#fn-4-602866a332ee5320), or else he endures pains to avoid worse pains.

This is Latin[↩︎](app://obsidian.md/index.html#fnref-1-602866a332ee5320)
There is a section mark but it does not show "Footnotes". Is that an option in settings? Actually it is.
[^Idea One]: Keep the text short so as to demonstrate only what is happening here.[↩︎](app://obsidian.md/index.html#fnref-2-602866a332ee5320)
This is a desirable quality.[↩︎](app://obsidian.md/index.html#fnref-3-602866a332ee5320)
The third note is found with pleasure.[↩︎](app://obsidian.md/index.html#fnref-4-602866a332ee5320)

**Comment by THIS-Usr** [comment]
It's a bit confusing, as I do not include the first two footnotes for the sake of brevity, and the pictures also record underlines from my editor tool that are irrelevant here.

**Comment by Comprehensive-Jason** [comment]
This numbering is normal behavior. Please read about how footnotes work in Obsidian [here](https://github.com/MichaBrugger/obsidian-footnotes/wiki/Footnote-Functionality). 

Also, footnote names can't have spaces in them, so `[^Idea One]` won't work but `[^Idea-One]` will.
