### ISSUE TITLE
Delete footnote feature

### ISSUE THREAD

**Issue by hermeneuticlens** [MichaBrugger/obsidian-footnotes#43]
Love this plugin SO MUCH! But is there a possibility of implementing a shortcut to delete the footnote, both reference and content, in one scoop? It would make our lives a lot easier if deleting a footnote is just as easy as adding a footnote through the plugin. Thanks!

**Comment by Comprehensive-Jason** [comment]
This was just added in Obsidian 1.7.1. You can right-click the footnote marker and click `Delete footnote and reference` to do just this.
