### ISSUE TITLE
Case sensitivity in autosuggest!

### ISSUE THREAD

**Issue by neuralgitwork** [MichaBrugger/obsidian-footnotes#44]
I love the autosuggest feature and often use upper-and lowercase letters intentionally for better readability and sometimes even for meaning. 
However, the autosuggestions aren't case-sensitive, so if I had some uppercase letters in my footnote's name, I'll have to type out the footnote manually every time, instead.

It would help a ton, in autosuggest was case-sensitive!

But might be just me or maybe there's even a good reason for it to be case-insensitive. ¯\\_(ツ)_/¯

**Comment by Comprehensive-Jason** [comment]
Autosuggest has been replaced by Obsidian Native footnote autocomplete. https://github.com/MichaBrugger/obsidian-footnotes/issues/42

Turn off this plugin's autosuggest feature and see if Obsidian's native autosuggest works for you.
