### ISSUE TITLE
Footnote link/tooltip not working while in editing mode

### ISSUE THREAD

**Issue by alexjayclark** [MichaBrugger/obsidian-footnotes#45]
Hello,

Love this plugin so much. One potential bug I've noticed, though maybe an intended feature — a footnote's link and tooltip are only working for me when I'm viewing a note in reading mode. Clicking or hovering on a footnote doesn't work while in editing mode, even if I've moved my typing cursor away from the line with the footnote. I was expecting this to still work in editing mode?

**Editing mode:**

![image](https://github.com/user-attachments/assets/45b42f9a-edc1-4de4-86fa-856c0d11d89b)

**Reading mode:**

![image](https://github.com/user-attachments/assets/644287c9-677b-489d-86b9-38332db749ee)

**Comment by Comprehensive-Jason** [comment]
The hover behavior is a new, Obsidian native feature added to the core page preview plugin in v1.6, and is not part of this plugin. Try holding `Cmd/Ctrl` while hovering over the footnote and see if what you want pops up. 

Feel free to ask me if that doesn't work. Best of luck!
