### ISSUE TITLE
Allow the heading level for the footnote section to be customizable

### ISSUE THREAD

**Issue by srs328** [MichaBrugger/obsidian-footnotes#48]
Right now the heading level for the footnote section is H1 size. The issue is that [Markdown conventions](https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md025.md) dictate that there should be only one top-level heading in a document. The H1 level should only be used for the title. 

It would be pretty straightforward to allow the user to set what level the footnote header should be automatically set to.

Thanks

**Comment by srs328** [comment]
If I have time, I'll try to implement it myself and submit a pull request.

**Comment by Comprehensive-Jason** [comment]
We are working on adding this feature in PR #47.

**Comment by churnish** [comment]
Need this! Can we get an ETA? 🙏

**Comment by Comprehensive-Jason** [comment]
@greetclammy Give me 2 weeks. I'll have this delivered during my college winter break.

**Comment by Mase3206** [comment]
I'm in the same boat. It should be ready for your testing and approval.
