### ISSUE TITLE
Named footnotes

### ISSUE THREAD

**Issue by Calorion** [MichaBrugger/obsidian-footnotes#7]
I use footnotes for various purposes, and would like to be able to use named footnotes rather than just numbered ones. Is there a way to do that with this plugin?

**Comment by SanJacobs** [comment]
I second this. At least make the plugin able to jump back and fourth using preexisting named footnotes.

**Comment by Comprehensive-Jason** [comment]
This feature would be amazing! 
I think it could work this way using a different `named footnote hotkey`. I will represent the cursor location with `|`.

Let's say I want to add a named footnote to the end of this line.
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.|
```

After I hit the `named footnote hotkey`, an empty footnote marker should be created where my cursor was and my cursor should be placed in the middle of the footnote marker like so:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[^|]
```

After I write my named footnote, I hit the `named footnote hotkey` again. The named footnote I wrote should show up at the bottom of the page and my cursor should be positioned to label it like how the plugin already works with numbered footnotes:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[^Named]

[^Named]: |
```

After I finish labeling, I hit the `named footnote hotkey` again. My cursor should jump to the end of the footnote marker, like how the plugin currently works with numbered footnotes:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[^Named]|

[^Named]: My label
```

I don't think this will be too difficult to implement. If I have time, I will try to add this to the plugin.

**Comment by Comprehensive-Jason** [comment]
@Calorion @SanJacobs I have added this feature in [my fork](https://github.com/Comprehensive-Jason/obsidian-footnotes). Until my pull request gets accepted, y'all can try it out using [Obsidian BRAT](https://github.com/TfTHacker/obsidian42-brat). Please make sure to read the README, as I have added new instructions for working with named footnotes.

**Comment by Comprehensive-Jason** [comment]
My fork has been merged into this plugin's latest release.
